#pragma once
#include "macros.h"

EXTERN_C_BEGIN


#ifndef CFG_TUSB_OS
#define CFG_TUSB_OS OPT_OS_FREERTOS
#define CFG_TUSB_OS_INC_PATH freertos/
#endif

#ifndef CFG_TUD_LOG_LEVEL
#define CFG_TUD_LOG_LEVEL 0
#endif

#ifndef CFG_TUH_LOG_LEVEL
#define CFG_TUH_LOG_LEVEL 0
#endif


#ifndef CFG_TUSB_DEBUG
#define CFG_TUSB_DEBUG 1
#endif


#define CFG_TUD_ENABLED 1
#define CFG_TUD_CDC 1
#define CFG_TUD_DFU 1
#define CFG_TUD_CDC_RX_BUFSIZE 4096
#define CFG_TUD_CDC_TX_BUFSIZE 4096
#define CFG_TUD_DFU_XFER_BUFSIZE 4096
#define TUD_OPT_RHPORT 0

#define CFG_TUH_ENABLED 1
#define CFG_TUH_MAX_SPEED OPT_MODE_FULL_SPEED
#define CFG_TUH_MAX3421 1
#define TUH_OPT_RHPORT 1

#ifndef CFG_TUH_MAX3421_ENDPOINT_TOTAL
#define CFG_TUH_MAX3421_ENDPOINT_TOTAL (8 + 4 * (CFG_TUH_DEVICE_MAX - 1))
#endif

#define CFG_TUH_ENUMERATION_BUFSIZE 256
#define CFG_TUH_HUB 0
#define CFG_TUH_DEVICE_MAX 1
#define CFG_TUH_MSC 0
#define CFG_TUH_HID 0


#define CFG_TUH_CDC 1
#define CFG_TUH_CDC_FTDI 0
#define CFG_TUH_CDC_CP210X 0
#define CFG_TUH_CDC_CH34X 0

#define CFG_TUH_CDC_RX_BUFSIZE 4096
#define CFG_TUH_CDC_TX_BUFSIZE 4096

#define CFG_TUH_CDC_LINE_CONTROL_ON_ENUM 0x00


#define CFG_TUH_CDC_LINE_CODING_ON_ENUM                                        \
  { 115200, CDC_LINE_CONDING_STOP_BITS_1, CDC_LINE_CODING_PARITY_NONE, 8 }

EXTERN_C_END